version: '2.14.0'

services:
  social-media:
    image: 'integrationsamples/springboot-reactive-social-media:0.0.1'
    ports:
      - '8087:8087'
    depends_on:
      sentiment-analysis: 
        condition: service_started
      mysql: 
          condition: service_healthy
    network_mode: "host"

  sentiment-analysis:
    image: 'shafreen/springboot-sentiment-api:0.0.1'
    ports:
      - '8088:8088'
    network_mode: "host"

  mysql:
    image: 'mysql:8-oracle'
    ports:
      - '3306:3306'
    network_mode: "host"
    environment:
      - MYSQL_ROOT_PASSWORD=dummypassword
      - MYSQL_DATABASE=social_media_database
      - MYSQL_USER=social_media_user
      - MYSQL_PASSWORD=dummypassword
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
    volumes:
      - "./resources/db/init.sql:/docker-entrypoint-initdb.d/1.sql"
